replicaCount: 1

image:
  repository: fmaulana24/pbo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
<<<<<<< HEAD
  tag: "v20"
=======
  tag: "v21"
>>>>>>> 3fca9cb (fix deployment error)

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000
